"""
Template and constitution loading, plus placeholder substitution.

Ports Get-KilnTemplate / Get-KilnConstitution / Get-KilnConstitutionHeader / Get-KilnRole /
Apply-Substitutions.

Templates are framework-owned (`src/kiln/resources/templates/`); the constitution and roles are
project-owned (`kiln/project/`) and are the user's to edit.
"""

from __future__ import annotations

import logging
import re
from pathlib import Path

from ..domain.paths import KilnPaths

log = logging.getLogger(__name__)

#: Blocks joined into a generated instruction file.
BLOCK_SEPARATOR = "\n\n---\n\n"

#: A role file's own loop sections are stripped before the role text is reused: the loop is
#: the wrapper's concern (or the scheduler's), never the worker's.
_LOOP_SECTION_RE = re.compile(r"(?ms)^## (?:Message Loop|Interaction Loop).*?(?=^## |\Z)")


class TemplateError(Exception):
    """A required template or constitution file is missing."""


def read_template(paths: KilnPaths, name: str) -> str:
    """Read a framework template by bare name (no extension)."""
    path = paths.templates_dir / f"{name}.md"
    if not path.is_file():
        raise TemplateError(f"missing framework template: {path}")
    return path.read_text(encoding="utf-8")


def read_constitution(paths: KilnPaths, name: str, required: bool = False) -> str:
    """
    Read a project constitution section (workflow / engineering / project).

    Only `workflow.md` is required — routing and the handoff format come from it, so a
    swarm cannot run without it. `project.md` and `engineering.md` are content the user
    may simply not have written yet, so a missing one degrades to an empty block with a
    warning rather than aborting the launch.
    """
    path = paths.constitution_dir / f"{name}.md"
    if not path.is_file():
        if required:
            raise TemplateError(f"missing required constitution section: {path}")
        log.warning("no %s.md in %s; continuing without it", name, paths.constitution_dir)
        return ""
    return path.read_text(encoding="utf-8")


def check_project_scaffolding(paths: KilnPaths) -> None:
    """
    Verify the project has been scaffolded, before any work is done.

    Without this the first missing file surfaces deep inside worker-file generation as a
    bare path, which tells the user nothing about the actual problem or the remedy.
    """
    if not paths.kiln_project_dir.is_dir():
        raise TemplateError(
            f"{paths.project_root} is not a scaffolded Kiln project "
            f"(no {paths.kiln_project_dir}).\n"
            f"       Run:  kiln init --working-dir {paths.project_root}\n"
            f"       Note: kiln/ must be committed. If it is gitignored, worktrees are "
            f"created without it."
        )

    workflow = paths.workflow_md
    if not workflow.is_file():
        raise TemplateError(
            f"missing {workflow}, which defines handoff routing and the message format.\n"
            f"       Run:  kiln init --working-dir {paths.project_root}"
        )


def read_constitution_header(paths: KilnPaths) -> str:
    """The optional `kiln/project/constitution.md` preamble; '' when absent."""
    path = paths.kiln_project_dir / "constitution.md"
    return path.read_text(encoding="utf-8") if path.is_file() else ""


def read_role(paths: KilnPaths, role: str) -> str:
    """
    Read a role definition with its loop sections removed.

    Returns '' when the role file does not exist — a profile may name a role the project has
    not written yet, and that should degrade rather than abort the launch.
    """
    path = paths.roles_dir / f"{role}.md"
    if not path.is_file():
        return ""
    stripped = _LOOP_SECTION_RE.sub("", path.read_text(encoding="utf-8")).lstrip("\r\n")
    return "# Role\n\n" + stripped


def apply_substitutions(text: str, substitutions: dict[str, str]) -> str:
    """Literal (non-regex) placeholder replacement, matching the PowerShell original."""
    for key, value in substitutions.items():
        text = text.replace(key, value)
    return text


def join_blocks(blocks: list[str], substitutions: dict[str, str] | None = None) -> str:
    """Drop empty blocks, substitute, and join with horizontal rules."""
    present = [block for block in blocks if block and block.strip()]
    if substitutions:
        present = [apply_substitutions(block, substitutions) for block in present]
    return BLOCK_SEPARATOR.join(present)


def generated_header(timestamp: str, comment_prefix: str = "<!--", suffix: str = "-->") -> str:
    """The 'do not edit' banner every generated file carries."""
    return (
        f"{comment_prefix} Auto-generated by kiln on {timestamp} {suffix}\n"
        f"{comment_prefix} DO NOT EDIT MANUALLY {suffix}\n\n"
    )


def resolve_framework_root(start: Path | None = None) -> Path:
    """
    Locate the Kiln checkout containing this package.

    This module lives at `<framework_root>/src/kiln/launcher/application`, so the root is
    five parent directories up. Computing it from `__file__` lets the launcher work when
    invoked by absolute path from anywhere.
    """
    here = (start or Path(__file__)).resolve()
    return here.parent.parent.parent.parent.parent
