"""
Worker context assembly. The scheduler reads the *same* generated agent file the legacy
in-session delegation path uses, so a worker cannot behave differently depending on which
path dispatched it.
"""

from __future__ import annotations

import json

import pytest
from scheduler import worker_prompt
from scheduler.status_contract import SENTINEL_PREFIX, parse_worker_report

# Shape produced by Write-GeneratedWorkerAgent (bin/kiln.ps1:955).
GENERATED_AGENT = """\
---
name: coder-worker
description: Performs the coder role's implementation work for one handoff cycle.
tools: Read, Write, Edit, Glob, Grep, Bash, PowerShell, Skill, NotebookEdit, TodoWrite
model: claude-sonnet-5
---

<!-- Auto-generated by kiln.ps1 on 2026-08-07 14:00:00 -->
<!-- DO NOT EDIT MANUALLY -->

# Coder Role

Implement via TDD.

---

# Project Rules

Python, pytest.
"""


class TestParsingGeneratedFiles:
    def test_reads_frontmatter_fields(self):
        definition = worker_prompt.parse_worker_definition(GENERATED_AGENT)
        assert definition.name == "coder-worker"
        assert definition.model == "claude-sonnet-5"
        assert definition.tools.startswith("Read, Write")
        assert "implementation work" in definition.description

    def test_body_excludes_frontmatter_and_keeps_role_content(self):
        definition = worker_prompt.parse_worker_definition(GENERATED_AGENT)
        assert "name: coder-worker" not in definition.prompt
        assert "# Coder Role" in definition.prompt
        assert "# Project Rules" in definition.prompt

    def test_generated_banner_comments_are_retained(self):
        # They are harmless context and dropping them would mean diverging from what the
        # in-session delegation path shows the same worker.
        assert "Auto-generated" in worker_prompt.parse_worker_definition(GENERATED_AGENT).prompt

    def test_model_is_optional(self):
        text = GENERATED_AGENT.replace("model: claude-sonnet-5\n", "")
        assert worker_prompt.parse_worker_definition(text).model is None

    def test_description_may_contain_colons(self):
        text = GENERATED_AGENT.replace(
            "description: Performs the coder role's implementation work for one handoff cycle.",
            "description: Coder: does the work",
        )
        assert worker_prompt.parse_worker_definition(text).description == "Coder: does the work"

    def test_leading_blank_lines_tolerated(self):
        assert worker_prompt.parse_worker_definition("\n\n" + GENERATED_AGENT).name == (
            "coder-worker"
        )

    @pytest.mark.parametrize(
        ("text", "message"),
        [
            ("no frontmatter here", "opening"),
            ("---\nname: x\nstill open", "closing"),
            ("---\ndescription: no name\n---\nbody", "no 'name'"),
        ],
        ids=["missing-open", "missing-close", "missing-name"],
    )
    def test_malformed_definitions_raise(self, text, message):
        with pytest.raises(ValueError, match=message):
            worker_prompt.parse_worker_definition(text)

    def test_load_from_disk(self, tmp_path):
        path = tmp_path / "coder-worker.md"
        path.write_text(GENERATED_AGENT, encoding="utf-8")
        assert worker_prompt.load_worker_definition(path).name == "coder-worker"

    def test_missing_file_raises_a_useful_error(self, tmp_path):
        with pytest.raises(FileNotFoundError, match="no generated worker agent"):
            worker_prompt.load_worker_definition(tmp_path / "absent.md")


class TestAgentsPayload:
    def test_is_valid_json_keyed_by_agent_name(self):
        definition = worker_prompt.parse_worker_definition(GENERATED_AGENT)
        payload = json.loads(worker_prompt.build_agents_payload(definition))
        assert set(payload) == {"coder-worker"}
        assert set(payload["coder-worker"]) == {"description", "prompt"}
        assert "# Coder Role" in payload["coder-worker"]["prompt"]

    def test_survives_quotes_and_newlines_in_the_body(self):
        text = GENERATED_AGENT.replace("Implement via TDD.", 'Use "quotes" and\nnewlines.')
        definition = worker_prompt.parse_worker_definition(text)
        payload = json.loads(worker_prompt.build_agents_payload(definition))
        assert 'Use "quotes" and\nnewlines.' in payload["coder-worker"]["prompt"]


class TestTaskPrompt:
    def _build(self, **overrides):
        args = {
            "handoff_text": "Sender: specifier\nHandoff: order-intake\nBuild the thing.",
            "role": "coder",
            "branch": "main",
            "worktree": "/repo/.worktrees/coder",
        }
        args.update(overrides)
        return worker_prompt.build_task_prompt(**args)

    def test_includes_the_handoff_verbatim(self):
        # Never a summary: anything the sender wrote must reach the worker intact.
        assert "Sender: specifier\nHandoff: order-intake\nBuild the thing." in self._build()

    def test_states_workspace_and_branch(self):
        prompt = self._build()
        assert "/repo/.worktrees/coder" in prompt
        assert "Branch: main" in prompt

    def test_appends_the_status_instruction(self):
        assert SENTINEL_PREFIX in self._build()

    def test_forbids_the_worker_from_owning_handoffs(self):
        assert "scheduler owns all of that" in self._build()

    def test_retry_includes_the_previous_failure(self):
        prompt = self._build(retry_of="KILN-STATUS: blocked missing fixtures")
        assert "Previous attempt failed" in prompt
        assert "missing fixtures" in prompt

    def test_first_attempt_has_no_retry_section(self):
        assert "Previous attempt failed" not in self._build()

    def test_instruction_examples_still_parse_from_the_assembled_prompt(self):
        # Guards the drift this module exists to prevent: whatever instruction text ends up
        # in front of the worker must be the text the parser understands.
        examples = [
            line.strip()
            for line in self._build().splitlines()
            if line.strip().upper().startswith(SENTINEL_PREFIX)
        ]
        assert {parse_worker_report(line).status for line in examples} == {"done", "blocked"}
