"""Infrastructure-independent ports required by the scheduler application."""

from __future__ import annotations

from pathlib import Path
from typing import Protocol

from .adapters import WorkerInvocation
from .models import DEFAULT_PRIORITY, QueueMessage, WorkerRequest


class MessageQueue(Protocol):
    def fetch(self, role: str, branch: str) -> QueueMessage | None: ...
    def fetch_resume(self, role: str, branch: str) -> QueueMessage | None: ...
    def mark_processing(self, message_id: str) -> bool: ...
    def mark_processed(self, message_id: str) -> bool: ...
    def mark_failed(self, message_id: str, error: str) -> bool: ...
    def count_arrivals(self, work_item: str, branch: str, target: str) -> int: ...
    def insert(
        self,
        sender: str,
        target: str,
        content: str,
        branch: str,
        priority: int = DEFAULT_PRIORITY,
        work_item: str | None = None,
    ) -> str: ...
    def exists(self, message_id: str) -> bool: ...
    def recover_processing(self, role: str, branch: str) -> list[QueueMessage]: ...


class Worktree(Protocol):
    def already_contains(self, target: str) -> bool: ...
    def merge(self, target: str, message: str): ...
    def squash_anchor(self) -> str: ...
    def has_commits_since(self, anchor: str) -> bool: ...
    def has_pending_changes(self) -> bool: ...
    def squash_since(self, anchor: str, message: str): ...
    def head_commit(self) -> str: ...
    def ensure_generated_ignored(self) -> None: ...
    def persist_inbound(self, content: str) -> Path | None: ...


class WorkerRunner(Protocol):
    def __call__(self, request: WorkerRequest) -> WorkerInvocation: ...
