"""Message queue port used by scheduler use cases."""

from typing import Protocol

from ...domain.models import DEFAULT_PRIORITY, InboundMessage, QueueMessage


class MessageQueue(Protocol):
    def fetch(self, role: str, branch: str) -> InboundMessage | None: ...
    def fetch_resume(self, role: str, branch: str) -> InboundMessage | None: ...
    def mark_processing(self, message_id: str) -> bool: ...
    def mark_processed(self, message_id: str) -> bool: ...
    def mark_failed(self, message_id: str, error: str) -> bool: ...
    def name_work_item(self, message_id: str, work_item: str) -> bool: ...
    def count_arrivals(self, work_item: str, branch: str, target: str) -> int: ...
    def insert(
        self,
        sender: str,
        target: str,
        content: str,
        branch: str,
        priority: int = DEFAULT_PRIORITY,
        work_item: str | None = None,
    ) -> str: ...
    def exists(self, message_id: str) -> bool: ...
    def recover_processing(self, role: str, branch: str) -> list[QueueMessage]: ...

    # Sequential-mode helpers -------------------------------------------------------
    def sequential_enabled(self, branch: str) -> bool: ...
    def next_backlog_task(self, branch: str) -> dict | None: ...
    def dispatch_backlog_task(
        self, identifier: str, branch: str, sender: str, target: str
    ) -> str: ...
