"""Version-control worktree port used by scheduler use cases."""

from pathlib import Path
from typing import Protocol


class CommandResult(Protocol):
    ok: bool
    stdout: str
    output: str


class Worktree(Protocol):
    def already_contains(self, target: str) -> bool: ...
    def merge(self, target: str, message: str) -> CommandResult: ...
    def squash_anchor(self) -> str: ...
    def has_commits_since(self, anchor: str) -> bool: ...
    def has_pending_changes(self) -> bool: ...
    def squash_since(self, anchor: str, message: str) -> CommandResult: ...
    def head_commit(self) -> str: ...
    def ensure_generated_ignored(self) -> None: ...
    def persist_inbound(self, content: str) -> Path | None: ...
